name: Deploy Frontend Angular

on:
  push:
    branches: [ "DESARROLLO" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, frontend] # Tu etiqueta personalizada

    steps:
      - name: Chequear código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Instalar PM2 Globalmente
        run: npm install -g pm2

      - name: Construir proyecto (Build)
        # Esto crea la carpeta 'dist'
        run: npm run build -- --configuration production

      - name: Desplegar con PM2 Serve
        shell: powershell
        env:
          PM2_HOME: C:\actions-runner-frontend\.pm2
        run: |
          # 1. Obtenemos la lista actual de procesos
          $pm2List = pm2 list

          # 2. Preguntamos: ¿La lista contiene el nombre "nexus-frontend"?
          if ($pm2List -match "nexus-frontend") {
              Write-Host "🔄 El proceso existe. Eliminando para actualizar..."
              pm2 delete nexus-frontend
          } else {
              Write-Host "✨ El proceso NO existe. Es un despliegue limpio."
          }

          # 3. Levantamos el servicio (Esto se ejecuta en ambos casos)
          # NOTA: Confirmé en tus logs que tu build genera 'dist/nexus.frontend' sin la carpeta /browser
          pm2 serve dist/nexus.frontend 4200 --spa --name "nexus-frontend"

          # 4. Guardamos la configuración
          pm2 save